export const FONT_SIZES = {
  default: '18px',
  text: '16px',
  scoreStrong: '40px',
  scoreStrongMobile: '35px',
  scoreStrongXsMobile: '28px',
  titleMain: '60px',
  titleMainLandscape: '50px',
  titleMainMobile: '40px',
  titleMainXsMobile: '30px',
  title1: '36px',
  title1Mobile: '30px',
  title1XsMobile: '26px',
  title2: '26px',
  title2XsMobile: '20px',
  title2Mobile: '22px',
  title3: '24px',
  title3Mobile: '20px',
  inputMobile: '16px',
  defaultMobile: '15px',
  medium: '14px',
  small: '12px',
  smallest: '10px',
  resultSummary: '24px',
  resultSummaryMobile: '19px',
  resultSummaryXsMobile: '18px',
};
