export const USER_ROUTES = {
  main: 'user',
  update: 'update',
  signUp: 'sign-up',
  signIn: 'sign-in',
  logOut: 'logout',
  getUserById: 'get-user-by-id',
  getUserByToken: 'get-user-by-token',
  updateProfilePassword: 'update-profile-password',
  updateResetedPassword: 'update-reseted-password',
  resetPasswordRequest: 'reset-password-request',
  createTrainerAdmin: 'create-trainer-admin',
  getUsersByTrainer: 'get-users-by-trainer',
  getAllUsers: 'get-all-users',
  getAllUsersRoleUser: 'get-all-users-role-user',
  getAllTrainers: 'get-all-trainers',
  getTrainersByUser: 'get-trainers-by-user',
  deleteUser: 'delete-user',
  deleteTrainer: 'delete-trainer',
  getAllUsersCsv: 'get-all-users-csv',
  getAllTrainersCsv: 'get-all-trainers-csv',
  getAllStudentsByTrainerCsv: 'get-all-students-by-trainer-csv',
  getUserHasPassword: 'has-password',
  getUserByEmail: 'get-user-by-email/:email',
  changeRole: 'change-role',
};
