export const IMAGES: Record<string, string> = {
  companyLogo: require('../assets/img/company-logo.svg').default,
  productLogo: require('../assets/img/product-logo.svg').default,
  mainPage: require('../assets/img/main-page.jpg').default,
  bannerResultMobile: require('../assets/img/banner-result-mobile.png').default,
  bannerResultLandscape: require('../assets/img/banner-result-landscape.png')
    .default,
  bannerResultDesktop: require('../assets/img/banner-result-desktop.png')
    .default,
  concernImage: require('../assets/img/concern.png').default,
  controlImage: require('../assets/img/control.png').default,
  curiosityImage: require('../assets/img/curiosity.png').default,
  confidenceImage: require('../assets/img/confidence.png').default,
  cooperationImage: require('../assets/img/cooperation.png').default,
  concernBodyImage: require('../assets/img/concern-body.svg').default,
  controlBodyImage: require('../assets/img/control-body.svg').default,
  curiosityBodyImage: require('../assets/img/curiosity-body.svg').default,
  confidenceBodyImage: require('../assets/img/confidence-body.svg').default,
  cooperationBodyImage: require('../assets/img/cooperation-body.svg').default,
  starLow: require('../assets/img/star-low.svg').default,
  starModerate: require('../assets/img/star-moderate.svg').default,
  starHigh: require('../assets/img/star-high.svg').default,
  superPower: require('../assets/img/superpower-icon.svg').default,
  close: require('../assets/img/close.svg').default,
  circleBackdrop: require('../assets/img/circle-backdrop.png').default,
  starTopBackdrop: require('../assets/img/star-backdrop.png').default,
  starBottomBackdrop: require('../assets/img/star-bottom-backdrop.png').default,
  ovalBackdrop: require('../assets/img/oval-backdrop.png').default,
  home: require('../assets/img/section-home.svg').default,
  assessment: require('../assets/img/section-assessment.svg').default,
  users: require('../assets/img/section-users.svg').default,
  userProfile: require('../assets/img/user.png').default,
  CareerFlex: require('../assets/img/career-flex.png').default,
  ['Career Design Game']: require('../assets/img/career-design-game.png')
    .default,
  ['My Career Adventure']: require('../assets/img/career-design-canvas.png')
    .default,
  ['Career Design Canvas']: require('../assets/img/my-career-adventure.png')
    .default,
  sectionLogo: require('../assets/img/logo-section.png').default,
  WORD: require('../assets/img/word-icon.png').default,
  LOGIC: require('../assets/img/logic-icon.png').default,
  SELF: require('../assets/img/self-icon.png').default,
  PEOPLE: require('../assets/img/people-icon.png').default,
  MUSIC: require('../assets/img/music-icon.png').default,
  BODY: require('../assets/img/body-icon.png').default,
  PICTURE: require('../assets/img/picture-icon.png').default,
  NATURE: require('../assets/img/nature-icon.png').default,
};
