export const IMAGES = {
  companyLogo: require('../assets/img/company-logo.svg').default,
  productLogo: require('../assets/img/product-logo.svg').default,
  back: require('../assets/img/back-arrow.svg').default,
  next: require('../assets/img/next-arrow.svg').default,
  mainPage: require('../assets/img/main-page.jpg').default,
  bannerResultMobile: require('../assets/img/banner-result-mobile.png').default,
  bannerResultLandscape: require('../assets/img/banner-result-landscape.png')
    .default,
  bannerResultDesktop: require('../assets/img/banner-result-desktop.png')
    .default,
  concernImage: require('../assets/img/concern.png').default,
  controlImage: require('../assets/img/control.png').default,
  curiosityImage: require('../assets/img/curiosity.png').default,
  confidenceImage: require('../assets/img/confidence.png').default,
  cooperationImage: require('../assets/img/cooperation.png').default,
  concernBodyImage: require('../assets/img/concern-body.svg').default,
  controlBodyImage: require('../assets/img/control-body.svg').default,
  curiosityBodyImage: require('../assets/img/curiosity-body.svg').default,
  confidenceBodyImage: require('../assets/img/confidence-body.svg').default,
  cooperationBodyImage: require('../assets/img/cooperation-body.svg').default,
  starLow: require('../assets/img/star-low.svg').default,
  starModerate: require('../assets/img/star-moderate.svg').default,
  starHigh: require('../assets/img/star-high.svg').default,
  superPower: require('../assets/img/superpower-icon.svg').default,
  close: require('../assets/img/close.svg').default,
  circleBackdrop: require('../assets/img/circle-backdrop.png').default,
  starTopBackdrop: require('../assets/img/star-backdrop.png').default,
  starBottomBackdrop: require('../assets/img/star-bottom-backdrop.png').default,
  ovalBackdrop: require('../assets/img/oval-backdrop.png').default,
};
