export const PROMISES_AREA = {
  printCaasPdf: 'get-caas-pdf',
  getCaasQuestionList: 'get-caas-questions',
  auth: 'sign-in',
  logOut: 'log-out',
  getCaasResult: 'get-caas-results',
  sendCaasAnswers: 'send-caas-answers',
  getCaasCsv: 'get-caas-csv',
  getCareerCanvasCsv: 'get-career-canvas-csv',
  getUserTrainers: 'get-user-trainers',
  requestTrainer: 'request-trainer',
  getGroupsByTrainer: 'get-groups-by-trainer',
  inviteStudent: 'invite-student',
  inviteFromSuperAdmin: 'invite-from-super-admin',
  sendCanvasAnswers: 'send-canvas-answers',
  printCareerCanvasPdf: 'print-career-canvas-pdf',
};
