export const ROUTES = {
  main: '/',
  quiz: '/caas-quiz',
  platform: '/platform',
  results: '/caas-quiz/results',
  pdf: '/caas-quiz/pdf',
  signIn: '/sign-in',
  signUp: '/sign-up',
  resetPassword: '/reset-password',
  updatePassword: '/password',
  dashboard: '/platform/dashboard',
  profile: '/platform/profile',
  history: '/platform/history',
  invitation: '/platform/invitation',
  trainer: '/platform/trainer',
  careerFlex: '/platform/careerFlex',
  careerDesignGame: '/platform/career-design-game',
  careerDesignCanvas: '/career-canvas',
  careerDesignCanvasResults: '/career-canvas/results',
  myCareerAdventure: '/platform/my-career-adventure',
  manageUser: '/platform/manage-user',
  manageGroup: '/platform/manage-group',
  manageTrainers: '/platform/manage-trainers',
  errorPage: '/error',
};
