export const baseHeaders = [
  'User Account ID',
  'User Name',
  'Email',
  'Report date and time',
  'Is Latest Version',
];

export const CareerCanvasQuestionsHeaders = [
  'WIT - word',
  'WIT - logic',
  'WIT - self',
  'WIT - people',
  'WIT - music',
  'WIT - body',
  'WIT - picture',
  'WIT - nature',
  'GRIT - curiosity',
  'GRIT - gratitude',
  'GRIT - grit',
  'GRIT - optimism',
  'GRIT - self-control',
  'GRIT - social intelligence',
  'GRIT - zest',
  'FIT - My goal, purpose or mission in life:',
  'FIT - value 1',
  'FIT - value 2',
  'FIT - value 3',
  'FIT - value 4',
  'FIT - Career Anchors - Technical Competence',
  'FIT - Career Anchors - Managerial Competence',
  'FIT - Career Anchors - Autonomy',
  'FIT - Career Anchors - Job Security',
  'FIT - Career Anchors - Lifestyle',
  'FIT - Career Anchors - Entrepreneurial',
  'FIT - Career Anchors - Service  dedication to a cause',
  'FIT - Career Anchors - Pure Challenge',
  'FIT - MBTI - I or E',
  'FIT - MBTI - S or N',
  'FIT - MBTI - T or F',
  'FIT - MBTI - J or P',
  'FIT - Holland Code - R',
  'FIT - Holland Code - I',
  'FIT - Holland Code - A',
  'FIT - Holland Code - S',
  'FIT - Holland Code - E',
  'FIT - Holland Code - C',
  'FIT - My preferred type of workmates:',
  'FIT - My favourite working conditions:',
  'FIT - My perfect place to live (now or in future)',
  'Skills - Core - Creative Thinking',
  'Skills - Core - Decision Making',
  'Skills - Core - Problem Solving',
  'Skills - Core - Sense Making',
  'Skills - Core - Transdisciplinary Thinking',
  'Skills - Core - Transdisciplinary Thinking',
  'Skills - Core - Building Inclusivity',
  'Skills - Core - Collaboration',
  'Skills - Core - Communication',
  'Skills - Core - Customer Orientation',
  'Skills - Core - Developing People',
  'Skills - Core - Influence',
  'Skills - Core - Adaptability',
  'Skills - Core - Digital Fluency',
  'Skills - Core - Global Perspective',
  'Skills - Core - Learning Agility',
  'Skills - Core - Self Management',
  'Skills - Technical',
  'Practicality check - My preferred salary range',
  "Practicality check - Career progression','Practicality check - Level/type of responsibility I'd like",
  'Practicality check - Other personal considerations',
];

export const allUsersHeaders = [
  'Name',
  'Group name',
  'Registered',
  'Email',
  'CareerFlex',
  'Career Flex Cooperation',
  'Career Design Canvas',
];
