export const ERRORS = {
  invalidToken: 'Invalid token',
  invalidRole: 'Invalid role',
  invalid: "Looks like that's the wrong password. Try again or reset.",
  tokenError: 'Token error',
  codeExpired: 'Code expired',
  linkExpired: 'Link expired',
  tokenExpired: 'Token expired',
  alreadyExist: 'Already exist',
  notExist: 'Not exist',
  loginError: 'Wrong email or/and password',
  needFood: 'Please add some food',
  notEnoughData: 'Not enough data',
  notFound: 'User not found',
};
