export const BreadCrumbTitle: { [key: string]: string } = {
  dashboard: `Dashboard`,
  platform: 'Main',
  history: 'History',
  home: 'Home',
  users: 'Users',
  invitation: 'Invite Users',
  'manage-user': 'Manage Users',
  'manage-trainers': 'Manage Trainers',
  'career-design-game': 'Career Design',
  'manage-group': 'Manage Group',
  'career-flex-admin': 'CareerFlex',
  'career-flex-plus-admin': 'CareerFlex+',
  'career-canvas-admin': 'Career Canvas',
  delete: 'Delete Account',
};
